# Generated by Django 3.1.5 on 2021-01-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_title', models.CharField(max_length=300, verbose_name='Название опроса')),
                ('start_date', models.DateField(verbose_name='Дата старта опроса')),
                ('end_date', models.DateField(verbose_name='Дата окончания опроса')),
                ('poll_description', models.TextField(verbose_name='Описание опроса')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('question_type', models.CharField(choices=[('text', 'Развернутый ответ'), ('one_opt', 'Выбор одного варианта ответа'), ('many_opt', 'Выбор нескольких вариантов ответа')], default='text', max_length=50, verbose_name='Тип вопроса')),
                ('polling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingsapp.polling')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300, verbose_name='Ответ')),
                ('votes', models.IntegerField(default=0, verbose_name='Проголосовали')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingsapp.question')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
    ]
